### ISSUE TITLE
CSGO close after injection

### ISSUE THREAD

**Issue by nguyentr4n14** [r4v10l1/NullHooks#14]
CSGO close after injection

**Comment by r4v10l1** [comment]
Okay, now I see what you mean, the update broke some stuff. There is a problem with `sig_key_values_engine` and `sig_key_values_client`.

Related: https://github.com/danielkrupinski/Osiris/issues/3709

**Comment by r4v10l1** [comment]
Yeah it is, I will update the signatures as soon as possible.

**Comment by r4v10l1** [comment]
Fixed in #15
