### ISSUE TITLE
[bug] Aimbot crash

### ISSUE THREAD

**Issue by Fanixtar** [r4v10l1/NullHooks#20]
### Bug description
Using aimbot crash client randomly

### Steps to reproduce
Using aimbot in casual match after some round
Using commit https://github.com/r4v10l1/NullHooks/commit/4f2326196b1f490c7374dd85399d2d3211e8fc07

**Comment by r4v10l1** [comment]
Probably fixed in 9823c97, but I will keep the issue open for now.

**Comment by r4v10l1** [comment]
I have been trying the aimbot in different gamemodes and I did not crash. I will close the issue but feel free to reopen again/open another issue if you need to.
