### ISSUE TITLE
[feature] Motion blur

### ISSUE THREAD

**Issue by MAHMA787** [r4v10l1/NullHooks#25]
Hey, I think you should add motion blur into the cheat, it would be a really cool feature.

You can see how it works from this source:
https://github.com/notgoodusename/OsirisAndExtra/commit/c6d97a95a86be624b8cd6f8cb11d1ac6da88d456

**Comment by r4v10l1** [comment]
I also think it could be a good addition. I will have a look.

**Comment by r4v10l1** [comment]
Implemented in 20bb16afc45cd9ce0c8e39f32506cd63b4f2293c, thanks for your suggestion.
