### ISSUE TITLE
[misc] motion blur amd fix

### ISSUE THREAD

**Issue by MAHMA787** [r4v10l1/NullHooks#28]
hey, if u want to fix the amd thing u only gotta detect if the user is an amd GPU and then apply this command mat_resolveFullFrameDepth 0

**Comment by hBuffer** [comment]
I have convarphobia

**Comment by r4v10l1** [comment]
Fixed in e4e007f98172611f1816fe8fdbd41a262004f871 (#31)

**Comment by hBuffer** [comment]
> Fixed in [e4e007f](https://github.com/r4v10l1/NullHooks/commit/e4e007f98172611f1816fe8fdbd41a262004f871) (#31)

this *should* fix it. lmk if there are any issues.
