### ISSUE TITLE
[bug] Screen size change breaks fonts.

### ISSUE THREAD

**Issue by hBuffer** [r4v10l1/NullHooks#33]
### Bug description
fonts break after screen size change.
![image](https://user-images.githubusercontent.com/105053604/177584895-7f709c63-ff98-4f2b-841f-8145d01c161a.png)

### Steps to reproduce
Settings -> Video -> Resolution

### (Optional) Possible fix
hook [OnScreenSizeChanged](https://gitlab.com/KittenPopo/csgo-2018-source/-/blob/main/public/vgui/ISurface.h#L320) and call [render::initialize](https://github.com/r4v10l1/NullHooks/blob/main/src/dependencies/utilities/renderer/renderer.cpp#L10)

**Comment by r4v10l1** [comment]
I have been aware of this problem for some time, but I didn't think it was very important.
I will try to fix it.
