### ISSUE TITLE
Menu framework suggestions

### ISSUE THREAD

**Issue by sanikbug2k18** [r4v10l1/NullHooks#4]
i like this source a lot, the framework seems ok but i think you should use imgui it would be better (my opinion), but if you want to use your framework then can you please put priority on keybind and listbox? :)

**Comment by r4v10l1** [comment]
As I said in another issue, right now I want to make my own framework. Once it's done, I might add ImGui (maybe in another brach, etc.) but for now I think I can learn more by making my own framework.

I will try to add those features as soon as I can.

**Comment by sanikbug2k18** [comment]
alright, good luck, it's a decent framework tho

**Comment by r4v10l1** [comment]
Added combobobx and hotkeys to the framework in the following commits:
- 8ca0ee14bad59da5ea0d255e67120eb79fbc2140
- 4f99f8eff0080984490ab3bdc8ffed7f54ff91b9
