### ISSUE TITLE
Aimbot And AutoFire

### ISSUE THREAD

**Issue by WhosOn** [r4v10l1/NullHooks#42]
The only on press for the aimbot feature is good but I don't want to press that specific button every time I want to use aimbot or auto-fire. You cant use normal silent nor normal aimbot cause of that feature.

**Comment by r4v10l1** [comment]
I think I understand what you mean, and you can already do that. I think what you want is having autofire always on, and not only when holding down the key (correct me if I'm wrong).

You can currently do that with the autowall or with any setting that uses a hotkey. From my readme:
> Hotkey system:
>   - `Delete` sets the hotkey to None, meaning that the hotkey will apear always as held
>   - `Esc` will cancel the current hotkey selection, restoring it to its original state

If you hover over the hotkey selection and press <kbd>Delete</kbd> or if you press delete while waiting for a hotkey, you will set it to "None", achieving what you wanted.

In case you are interested in the code, Line 98:
https://github.com/r4v10l1/NullHooks/blob/24bbfc78289c14e2981a05fd76334056f6c655d8/src/core/menu/global_input.hpp#L96-L104

**Comment by WhosOn** [comment]
Thank you <3
