### ISSUE TITLE
[bug] Aimbot fov not working

### ISSUE THREAD

**Issue by WhosOn** [r4v10l1/NullHooks#47]
The draw fov doesn't work

**Comment by r4v10l1** [comment]
>In the description provide the following:
>    - Detailed description of the buggy behavior.
>    - As many reproduction steps as you can provide.
>    - Optionally a fix that you found.

Can you please explain what settings were you using and what exactly do you mean by "doesn't work"?

I can use it perfectly:
![image](https://user-images.githubusercontent.com/29655971/180515847-560e28bb-125c-4a51-8e8f-893d0a6497e3.png)

**Comment by WhosOn** [comment]
hold up ima try it again

**Comment by WhosOn** [comment]
but before it wasn't drawing fov ima see if it works

**Comment by WhosOn** [comment]
![image](https://user-images.githubusercontent.com/92133353/180583441-3a09a3e5-3521-46b0-835e-9eac0a62c4fd.png)

**Comment by WhosOn** [comment]
as you can see in the picture i have it turned on but it doesnt draw the fov circle nor square

**Comment by WolfyCSGO** [comment]
maybe cuz that fov is bigger then u r resolution ?

**Comment by hBuffer** [comment]
[feature] 1080p FOV square

**Comment by r4v10l1** [comment]
S- sir... You are using 180 fov...

If I send my settings and you see it works, why don't you try applying them and seeing what happens?
