### ISSUE TITLE
[bug] Crash when injecting or loading map

### ISSUE THREAD

**Issue by POWERzzzzz** [r4v10l1/NullHooks#54]
tried injecting into a bot game, crashed, injected to main menu and then loaded into bot game, when i was about to be able to choose team, crash

**Comment by r4v10l1** [comment]
As I said multiple times, can you provide any details about:
  - Your injector
  - The `.dll` you are using (Compiled from source or from the releases page)
  - Did you follow the installation process from the readme?

I am using the latest build and I can use it without problems, so I need to know more details.

If you know how, try compiling in debug mode and attach a debugger.

**Comment by POWERzzzzz** [comment]
im sorry had the wrong injection method thing in XD
