### ISSUE TITLE
[bug] Autofire not shooting with some guns

### ISSUE THREAD

**Issue by WhosOn** [r4v10l1/NullHooks#55]
When you push your auto fire key, it doesnt fire sometimes, also sometimes it doesnt work with guns it will only work with ak, and scar20 nothing else.

**Comment by WhosOn** [comment]
Could be a fov issue but it has worked before so idk

**Comment by r4v10l1** [comment]
You already made a similar issue without posting your settings and I told you about it...

This time I will try to guess your error. If your weapon can't deal your minimum damage it is not going to shoot... If using aimbot with 0 minimum damage does not work, try posting your settings.

**Comment by WhosOn** [comment]
I had minimum at 100. i feel retarded rn.

**Comment by WhosOn** [comment]
i didnt even notice sryy homie..
