### ISSUE TITLE
[feature] Anti-votekick

### ISSUE THREAD

**Issue by WhosOn** [r4v10l1/NullHooks#56]
THIS WILL BE THE BEST FEATURE EVER. in skeet/ nanosense paste or gamesense. They have a Anti - Kick / Anti - ban feature which what it does is "Force Vote Failed/ F2".

**Comment by r4v10l1** [comment]
I am really not sure what you mean or how to achieve this... 🤷🏻‍♂️

**Comment by WhosOn** [comment]
ill try to search for it one sec. but if we get to implement it. the cheat gon be on another level

**Comment by rrhyast** [comment]
> THIS WILL BE THE BEST FEATURE EVER. in skeet/ nanosense paste or gamesense. They have a Anti - Kick / Anti - ban feature which what it does is "Force Vote Failed/ F2".

you mean **anti afk kick or anti vote kick?**

**Comment by r4v10l1** [comment]
> **ANTI AFK KICK OR ANTI VOTE KICK?**

Yeah I really don't know what this is about...

**Comment by WhosOn** [comment]
Anti Vote Kick

**Comment by WhosOn** [comment]
i have game sense src i could slide it and you can implement it if u want. just msg me back and tell me

**Comment by r4v10l1** [comment]
I have never seen that. If you can provide more details I will try to add it.

**Comment by rrhyast** [comment]
> Anti Vote Kick



> I have never seen that. If you can provide more details I will try to add it.

let me make it simple for you. in 2020 i found a lua for nixware that change the name of the vote kicker without anyone notice, but it doesn't have any option to change the name of the person that going to  be vote kicked. if u can make some extra tab for it to set vote kicker name & set victim name (based on playerlist names) it works very well.

if  i found the lua script I'll post it here. (you will understand it better)

**Comment by r4v10l1** [comment]
But what does that have to do with:
> "Force Vote Failed/ F2"

As far as I know what @WhosOn is asking is not a "spoofer", but a complete votekick bypass, which I don't think its possible.

**Comment by r4v10l1** [comment]
I am closing the issue because there is no information about this that I know of. If you have more information feel free to post a comment and reopen the issue.
