### ISSUE TITLE
[feature]

### ISSUE THREAD

**Issue by WhosOn** [r4v10l1/NullHooks#57]
Inventory Changer. Its basically allows you to give you skins. *TEMP*  / Soft Unlock

**Comment by WhosOn** [comment]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/328741-inventory-changer.html

**Comment by WhosOn** [comment]
https://www.unknowncheats.me/forum/counterstrike-global-offensive/271136-inventory-changer-protobuf.html

**Comment by WhosOn** [comment]
https://github.com/danielkrupinski/Osiris 


SRC

**Comment by WhosOn** [comment]
https://github.com/namazso/nSkinz

SRC

**Comment by r4v10l1** [comment]
There is a skin changer. Read the README.
