### ISSUE TITLE
[bug] Might Be With Cheat OR Might Not Be

### ISSUE THREAD

**Issue by WhosOn** [r4v10l1/NullHooks#60]
When im using the cheat i get this

![image](https://user-images.githubusercontent.com/92133353/181342343-7a489488-8da5-4cb4-adc6-d3926028a8e1.png)

**Comment by WhosOn** [comment]
I already did all the steps in the website

**Comment by WhosOn** [comment]
Its only when i use the cheat. *NOT RAGE*

**Comment by WhosOn** [comment]
I Use 

![image](https://user-images.githubusercontent.com/92133353/181342468-f38fd745-4504-4a14-969a-847402dc96e2.png)

**Comment by r4v10l1** [comment]
1. What do you mean not rage.
2. YOU DONT HAVE TO MAKE 12315314 COMMENTS FOR ALL THIS SHIT.
