### ISSUE TITLE
[feature] AntiAim keybinds

### ISSUE THREAD

**Issue by POWERzzzzz** [r4v10l1/NullHooks#65]
Money Revealer
Rank Revealer
Standalone RCS (w/o aimbot) 

Having the ability to completely UNBIND stuff (unless thats already possible but i wouldn't know how.)

Perhaps a standalone skinconfig configuratorinator-3000

keybinds for anti aim to invert position (like to turn a different direction without needing to reposition the slider)

**Comment by r4v10l1** [comment]
What do you mean by "unbind" stuff? Check this issue: #42 

The skin changer is configured by modifying the `skins.json` file located under `DOCUMENTS/NullHooks/skins.json`. There is no menu for skinchanger because I am not sure what the best way of adding that would be.

I will try to add a keybind for the aa thing.

**Comment by POWERzzzzz** [comment]
Ah yes, I see that's what I meant. 

I know about the skinchanger, however it's a lot of work and there's no visual interface. ( i know this is probably a huge amount of work again and not at the top of your priorities but it could be a way for you to add it in the future). I'd prefer it being a standalone app as to not bloat up the menu with more stuff, since it's probably also laggy to load a bunch of images. 

I hope the first 3 features are also being considered, many thanks already for the work that's been done, i really enjoy the menu.

**Comment by r4v10l1** [comment]
Yeah, as you said that's the problem with the skinchanger, making a good user interface for the skins. Images might be a bit too much and if I just make a list with the skin names it would take a lot of space, and the framework currently doesn't have anything to "scroll", etc.

I am adding the antiaim key now and I will try to add the other features. Closing the issue.

**Comment by r4v10l1** [comment]
"Peek antiaim" added in 3e137f08c54719b778b373cc3adc9f12de70d992

**Comment by r4v10l1** [comment]
Rank revealer added in 1be06cea388f213bba53b45f488b9a685126307a
