### ISSUE TITLE
[bug] Headshot multiplier is not the same for all weapons

### ISSUE THREAD

**Issue by deboogerxyz** [r4v10l1/NullHooks#66]
Reference (SlothSquadron's weapon spreadsheet): https://docs.google.com/spreadsheets/d/11tDzUNBq9zIX6_9Rel__fdAUezAQzSnh5AVYzCP060c
The solution: https://github.com/danielkrupinski/Osiris/blob/master/Source/SDK/WeaponData.h#L40

**Comment by r4v10l1** [comment]
mfw you link the osiris struct instead of my struct 👿

**Comment by deboogerxyz** [comment]
i aint gon search your code, i have more important things to do

**Comment by r4v10l1** [comment]
Fixed in a174a66a4224803c982300a9d0d80943ef660b8f 👍🏻
