### ISSUE TITLE
Backtrack - Valid Tick (Changes +Explanation)

### ISSUE THREAD

**Issue by Ceaco1337** [r4v10l1/NullHooks#68]
```cpp
if (records[i].size() && (records[i].front().simulation_time == entity->simulation_time())) continue;
```
You're first checking for if you have records for the current entity.
Then the newest record created with the current entity simulation time.

Remember that the update function is getting called constantly. 
You don't want to have 9999 records of a player from the  exact same tick.
Which would still be within your "backtrack range" meaning they won't get deleted.

Some people only created records when the player moved.
But that means you couldn't backtrack lby flicks from old hvh fake angles. 
Or if the player is jittering but standing still.

So you create a new record every time the enemy's sim time updates.

-----------
Remove `float maxtime` from: (unless above is changed)
```cpp
bool backtrack::valid_tick(float simtime, float maxtime)
```
As you are not using it at all. With all `valid_tick` usages having `0.2f` as the parameter.

```cpp
// The following lines determine if the tick is valid or not. We erase all the invalid ones
auto invalid = std::find_if(std::cbegin(records[i]), std::cend(records[i]), [](const player_record& rec) {
   return !valid_tick(rec.simulation_time, 0.2f);
```
```cpp
if (!record || !valid_tick(record->simulation_time, 0.2f)) continue;
```
It would be fine if you were planning to use it to clamp your records to your slider, but you already have:
```cpp
while (records[i].size() > 3 && records[i].size() > static_cast<size_t>(TIME_TO_TICKS(variables::misc::backtrack_ticks / 1000.f)))
   records[i].pop_back();
```
You really should just have your "valid_tick" be handling it. (Maybe even use that maxtime you put)

-----------
Remove
```cpp
float time_limit = maxtime;
std::clamp(time_limit, 0.001f, 0.2f);
```
Clamping this is dumb, using any fake latency will delete the record past the 200ms area.
Meaning if you use fake latency, you will not be able to draw or backtrack past the 200ms default limit.
Make it more like:
```cpp
// if your fake latency slider is gonna be from 0 - 200
float time_limit = (your ping spike setting) ? (0.2f + fake latency) : 0.2f

// or if your fake latency slider is (200 min -> 400 max)
float time_limit = (your ping spike setting) ?  fake latency : 0.2f
```
I'd personally just delete the clamp, as you also don't even use anything but 0.2f for the parameter

-----------
Change:
```cpp
float delta_time = correct - (TICKS_TO_TIME(csgo::local_player->get_tick_base()) - simtime);
```
To:
```cpp
float delta_time = correct - (TICKS_TO_TIME(interfaces::globals->cur_time) - simtime);
```
I'm assuming you're using tick base due to: https://www.unknowncheats.me/forum/2137042-post9.html ?
a8pure is wrong here:

source-sdk-2013 uses tickcount, and hl2sdk-csgo uses curtime:
```cpp
// source-sdk-2013
float deltaTime =  correct - ( gpGlobals->tickcount - flTargetTime );

//  hl2sdk-csgo
float deltaTime =  correct - ( gpGlobals->curtime - flTargetTime );
```
-----------
Finished should be:
```cpp
bool backtrack::valid_tick(float simtime) noexcept {
	auto nci = interfaces::engine->get_net_channel_info();
	if (!nci) return false;

	// do these computations in float time, not ticks, to avoid big roundoff error accumulations in the math
	// true latency + network latency + interpolation latency (lerp time)
	float correct = nci->get_latency(0) + nci->get_latency(1) + get_lerp_time();

	// check to see if our correction is within 0 - sv_maxunlag
	std::clamp(correct, 0.f, interfaces::console->get_convar("sv_maxunlag")->get_float());

        // calc difference between tick sent by player and our latency based tick
	float delta_time = correct - (TICKS_TO_TIME(interfaces::globals->cur_time) - simtime);

       // don't include these last 3 comments
       // add support for fake latency eventually (which should be dynamic to 0.2f -> 0.4f)
       // or if your are using maxtime for clamping record count, then use that instead of 0.2f
	return fabsf(delta_time) <= 0.2f;
}
```

**Comment by r4v10l1** [comment]
Thank you for making such a good and complete issue. I will add your suggestions and explain the changes.

**Comment by r4v10l1** [comment]
Added in 6c9f6df4e2d519a7e0525a16e4998c90b7c5303e 👍🏻
