### ISSUE TITLE
Hello, I'm from China. Your apex hackers have a very vast market in China. How can I contact you and learn from you?

### ISSUE THREAD

**Issue by sewujishipin** [r4v10l1/NullHooks#7]
Hello, I'm from China. Your csgo hackers have a very vast market in China. How can I contact you and learn from you?

**Comment by sewujishipin** [comment]
We have a complete sales channel, which can help your csgo hackers sell in China and make huge profits

**Comment by r4v10l1** [comment]
Stop making retarded issues please.

Daily reminder to read the [contributing guidelines](https://github.com/r4v10l1/NullHooks/blob/main/CONTRIBUTING.md).
