### ISSUE TITLE
how do I change the tab location

### ISSUE THREAD

**Issue by Limitrious** [r4v10l1/NullHooks#92]
how do I change the tab location like from top to left or top to bottom. I've been looking at other base like designer1337's base, csgo_sdk and even legendware but still cannot find out how to do it. I tried modifying menu.ccp tabs section and framework.cpp dynamic gui section. Im new at making/pasting cheat, sorry if this is a stupid question but I need to understand these basic stuff in order to add/modify features or even making my own cheat.

**Comment by 8dcc** [comment]
I don't really understand what you are asking, sorry.

**Comment by Limitrious** [comment]
> I don't really understand what you are asking, sorry.
> 
> Keep in mind that my GUI framework is heavily modified from designer's original code.

sorry for my bad english, here i some image, hope u can understand what i meant 
https://imgur.com/a/5bDwlUk
I want to make nullhooks tab (i mean aim, visual, ...) to be in the left like designer's base

**Comment by 8dcc** [comment]
As I said, my framework is pretty much a different one from designer's, and you would have to change a lot of stuff.

If you want tabs on the left, just use/modify designer's base.
